### ISSUE TITLE
Responsive menu doesn't work

### ISSUE THREAD

**Issue by perteraul** [koskz/booty#4]
I'm trying to trigger the responsive menu and after I click on it, it stays in a hover state forever.

**Comment by lochoe** [comment]
after one year, menu still not working

**Comment by unloft** [comment]
Hi  @perteraul @lochoe @kostyakoz 
I fix this issue:

add this **id**  in nav bar tag on line 69 in posts.php file (_your_anchor_folder/themes/booty-master/posts.php_)

`<nav id="myTopnav"   .......>`

add this onClick function in button tag (same file as before on line 58)

`onclick="myFunction()"`

add this script in footer (_your_anchor_folder/themes/booty-master/footer.php_)

```
<script type="text/javascript">
	
function myFunction() {
    var x = document.getElementById("myTopnav");
    if (x.className === "topnav") {
        x.className += " collapse navbar-collapse bs-navbar-collapse";
    } else {
        x.className = "topnav";
    }
}
</script>
```


**# now the responsive function should work !**
# **ENJOY!**
